Temporary fix for missing internalBinding
ReferenceError: internalBinding is not defined
https://github.com/gulpjs/gulp/issues/2246#issuecomment-435646661
Note: Upgrading to gulp 4 is the long-term fix.